version: '3'

networks:
  proxy_net:

services:
  proxy_service:
    build: ./nginx
    networks:
      proxy_net:
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy:/etc/nginx/conf.d

  api_service:
    build: ./nginx
    networks:
      proxy_net:
    volumes:
      - ./nginx/api:/etc/nginx/conf.d
      - ./api:/var/www/

  admin_service:
    build: ./nginx
    networks:
      proxy_net:
    volumes:
      - ./nginx/admin:/etc/nginx/conf.d
      - ./admin:/var/www